import Head from 'next/head'
import "../styles/globals.css"

function MyApp({ Component, pageProps }) {
  return (
    <div>
      <Head>
        <title>Musify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='max-w-7xl w-full mx-auto'>
        <Component {...pageProps} />
      </div>
    </div>
  )
}

export default MyApp
